# =======================================
#  BossBarTrainAnnounce
# =======================================
# @author     rypengu23
# @copyright  Copyright ryoengu23 2021
version: 1.1
language: "ja"
# =======================================

# DB接続先情報
# MySQLのみ対応

database:
 hostname: "localhost:3306"
 db: "test"
 user: "user"
 password: "password"

# ポジションセット用アイテム
# アナウンス地点の選択時に使用するアイテムを選択
select:
  item: "GOLDEN_AXE"

# その他設定
setting:
 prefix: "BBTA"

 # 乗り換え取得半径
 transferRange: 200

 # アナウンス送信間隔(tick)
 # アナウンス1通1通の間隔を設定
 announceInterval: 50L
